name: sgcgo
description: A Flutter project for environmental monitoring
publish_to: "none" # không dùng trên pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_selector: ^0.9.0
  url_launcher: ^6.3.2
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/phan_cap.json
    - assets/tieu_chuan.json
